import os

DEMAND_API_URL= os.getenv('CROWDEMOTION_DEMAND_API_URL')
DEMAND_API_CLIENT_ID= os.getenv('CROWDEMOTION_DEMAND_API_CLIENT_ID')
DEMAND_API_PASSWORD= os.getenv('CROWDEMOTION_DEMAND_API_PASSWORD')
DEMAND_API_USERNAME= os.getenv('CROWDEMOTION_DEMAND_API_USERNAME')
APP_SECRET_KEY = os.getenv('CROWDEMOTION_APP_SECRET_KEY')
CACHE_DEFAULT_TIMEOUT = int(os.getenv('CROWDEMOTION_CACHE_DEFAULT_TIMEOUT', "300"))
API_USER = os.getenv('CROWDEMOTION_API_USER')
API_PASSWORD = os.getenv('CROWDEMOTION_API_PASSWORD')